version: "3"
services:
  socket:
    image: node:10.15.2
    ports:
      - "3015:3015"
    volumes:
      - .:/socket
    command: bash -c "npm install && node socket.js"
    networks:
      - traefik_public
    deploy:
      labels:
        - traefik.enable=true
        # - traefik.http.routers.directus.entrypoints=https
        # - traefik.http.routers.directus.rule=Host(`directus.sw.hybrid-class.gr`)
        # - traefik.http.routers.directus.service=directus
        # - traefik.http.services.directus.loadbalancer.server.port=8055
        - traefik.docker.network=traefik_public
      placement:
        constraints:
          - node.role == manager
networks:
  traefik_public:
    external: true