version: "3"
services:
  socket:
    image: node:10.15.2
    ports:
      - "3015:3015"
    volumes:
      - /mnt/storage-pool/socket:/socket
    command: bash -c "cd socket && npm install && node index.js"
    networks:
      - traefik_public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.socket.entrypoints=https
        - traefik.http.routers.socket.rule=Host(`socket.sw.hybrid-class.gr`)
        - traefik.http.routers.socket.service=socket
        - traefik.http.services.socket.loadbalancer.server.port=3015
        - traefik.docker.network=traefik_public
      placement:
        constraints:
          - node.role == manager
networks:
  traefik_public:
    external: true